server:
  port: 8688
  jetty:
    threads:
      acceptors: 2 # 接收连接的线程数
      selectors: 4 # 处理连接的线程数
      max: 20 # 最大的线程数
      min: 4 # 最小的线程数
spring:
  application:
    name: pgcrowd2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://52.199.163.241:5432/pgcrowd2
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    open-in-view: false
  output:
    ansi:
      enabled: ALWAYS
  freemarker:
    cache: false
    allow-request-override: true
    expose-request-attributes: false
    allow-session-override: true
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/templates/
    suffix: .ftl
    settings:
      {datetimeFormat: yyyy-MM-dd HH:mm:ss, templateUpdateDelay: 0s}